# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- services/.*

handlers:
# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
# https://cloud.google.com/appengine/docs/python/how-requests-are-routed
- url: /.*
  script: main.app

builtins:
# Appstats
# https://cloud.google.com/appengine/docs/python/tools/appstats?hl=en
- appstats: off

libraries:
- name: ssl
  version: latest

includes:
# Include specific conditions based on environment
- dev_env_variables.yaml
#- production_env_variables.yaml

# [END runtime]
