# [START runtime]
runtime: python27
api_version: 1
threadsafe: yes

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- services/.*

handlers:
# This handler tells app engine how to route requests to a WSGI application.
# The script value is in the format <path.to.module>.<wsgi_application>
# where <wsgi_application> is a WSGI application object.
# https://cloud.google.com/appengine/docs/python/how-requests-are-routed
- url: /tasks/.*
  script: main.app
  login: admin
#  secure: always

- url: /.*
  script: main.app
#  secure: always

builtins:
# Appstats
# https://cloud.google.com/appengine/docs/python/tools/appstats?hl=en
- appstats: off

libraries:
- name: ssl
  version: latest

env_variables:
  SETTINGS_PATH: /settings.cfg

# [END runtime]
